name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@0dcf370eb08b3f884992181348b8c41d7f66c10e # main
        with:
          repository: openstack/manila
          ref: 53ccaa57baf88aa47635754e9b40e8e3d81ca936 # stable/2025.1

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@0dcf370eb08b3f884992181348b8c41d7f66c10e # main
        with:
          image-name: manila
          build-contexts: manila=openstack/manila
          push: ${{ github.event_name != 'pull_request' }}
