name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  tox:
    name: tox (${{ matrix.project.repository }})
    uses: vexxhost/docker-atmosphere/.github/workflows/tox.yml@5923a8fba3a98cf17e36583cc498d5e70a01c482 # main
    strategy:
      fail-fast: false
      matrix:
        project:
          - repository: openstack/manila
            ref: 75f247b92eb4fd269a52483e65274ecf1c1fa0f5 # master
    with:
      repository: ${{ matrix.project.repository }}
      ref: ${{ matrix.project.ref }}

  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@d763fd8920390074628431db771a56ab4f7aa8e2 # main
        with:
          repository: openstack/manila
          ref: 067c419e33bf137c62822307e4d3016579e49a86 # master

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@d763fd8920390074628431db771a56ab4f7aa8e2 # main
        with:
          image-name: manila
          build-contexts: manila=openstack/manila
          push: ${{ github.event_name != 'pull_request' }}
